# Generated by Django 6.0.1 on 2026-01-13 13:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='license_number',
            field=models.CharField(max_length=8, unique=True, validators=[django.core.validators.MinLengthValidator(8), django.core.validators.MaxLengthValidator(8), django.core.validators.RegexValidator(message='There must be exactly 8 characters:the first 3 are uppercase letters,the last 5 are numbers.', regex='^[A-Z]{3}\\d{5}$')]),
        ),
    ]
